# -*- coding: utf-8 -*-
"""ca2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fyK2enWvuVAeT7OUV4pDvJJrpS_uocej
"""

import os,sys
from google.colab import drive 
drive.mount('/content/drive')
os.chdir("/content/drive/My Drive/Colab Notebooks/")
sys.path.append("/content/drive/My Drive/Colab Noteboos/")

# Commented out IPython magic to ensure Python compatibility.
# step 1 importing libraries  
# we are using pandas dataframe 
# numpy stands for numerical python , is a  python package
# matplotlib is a graph plotting library in python  used for visualizing the results 

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# %matplotlib inline 
import seaborn as sns 

# load dataset from drive

datasets = pd.read_csv('Social_Network_Ads.csv')

datasets

datasets.info

datasets.isnull().sum()

#for train the model we choose two columns, age and estimated salary 
 
from typing import ValuesView
x=datasets.iloc[:,[2,3]].values
y=datasets.iloc[:,4].values

from re import X

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.25,random_state=0)

from sklearn.preprocessing import StandardScaler

sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)
y_pred

y_test

#here we can see some of our prediction went wrong

#accuracy test
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

